### ISSUE TITLE
实现dict数据结构

### ISSUE THREAD

**Issue by zhangzhimin** [matazure/prajna#2]
需要实现dict数据结构,  采用哈希表实现, 和std::unorder_map对标.

**Comment by haobosang** [comment]
这个我来尝试一下

**Comment by Kensuke-Hinata** [comment]
想了解一下具体应对的场景，请问有具体的proposal么？

**Comment by zhangzhimin** [comment]
> 想了解一下具体应对的场景，请问有具体的proposal么？

目前没有具体的proposal, 回头会写个文档来介绍般若编程语言的特性. 大家如果有建议可以在Discussions里提出讨论
