### ISSUE TITLE
向下/向上取整结果不正确

### ISSUE THREAD

**Issue by haobosang** [matazure/prajna#27]
浮点数精度问题：浮点数在计算机中是以二进制形式存储的，因此在进行浮点运算时，可能会出现舍入误差。如果输入的浮点数精度过高，可能会导致向下取整的结果出现偏差。

**Comment by zhangzhimin** [comment]
这个应该是解析浮点数的时候除了错误

**Comment by zhangzhimin** [comment]
是精度问题, float16的精度较低, 所以容易出现这个问题
