### ISSUE TITLE
推荐使用mdBook制作文档

### ISSUE THREAD

**Issue by microctar** [matazure/prajna#30]
mdBook 设置清晰,  能直接以markdown格式阅读, 也能生成带搜索的html文档。

介绍页面: https://rust-lang.github.io/mdBook

**Comment by zhangzhimin** [comment]
目前暂不使用markdown, 需要的可以开发者自己生成, 我们按照规范的方式去写markdown就好了.

直接使用Jupyter来书写部分文档, 集成般若运行环境更适合初学者边学边试
