### ISSUE TITLE
Prajna的JIT沙盒隔离

### ISSUE THREAD

**Issue by zhangzhimin** [matazure/prajna#33]
Prajna是不会去检测Array, Tensor等的越界操作, 其可以直接操作内存, 所以会不可避免的存在程序崩溃的情况.

研究下是否有比较合理的进程隔离方案, 来避免程序的崩溃. 将Repl的Workspace和编译信息保存在其他进程?  使用进程隔离?

**Comment by microctar** [comment]
可以把檢查越界操作做成可選項，用戶自己決定要不要啓用。

**Comment by microctar** [comment]
ANSEL, Jason, et al. Language-independent sandboxing of just-in-time compilation and self-modifying code. In: Proceedings of the 32nd ACM SIGPLAN conference on Programming language design and implementation. 2011. p. 355-366.

**Comment by microctar** [comment]
https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/37204.pdf

**Comment by microctar** [comment]
## Process Isolation in Firefox

https://mozilla.github.io/firefox-browser-architecture/text/0012-process-isolation-in-firefox.html

**Comment by microctar** [comment]
KROLL, Joshua A.; STEWART, Gordon; APPEL, Andrew W. Portable software fault isolation. In: 2014 IEEE 27th Computer Security Foundations Symposium. IEEE, 2014. p. 18-32.

https://www.cs.princeton.edu/~appel/papers/psfi.pdf

**Comment by microctar** [comment]
SEREBRYANY, Konstantin, et al. Addresssanitizer: A fast address sanity checker. 2012.

https://www.usenix.org/system/files/conference/atc12/atc12-final39.pdf?ref=https://githubhelp.com

**Comment by microctar** [comment]
Hongwei Xi and Frank Pfenning. 1998. Eliminating array bound checking through dependent types. SIGPLAN Not. 33, 5 (May 1998), 249–257. https://doi.org/10.1145/277652.277732

https://www.cs.cmu.edu/~fp/papers/pldi98dml.pdf

**Comment by microctar** [comment]
Ali-Reza Adl-Tabatabai, Michał Cierniak, Guei-Yuan Lueh, Vishesh M. Parikh, and James M. Stichnoth. 1998. Fast, effective code generation in a just-in-time Java compiler. In Proceedings of the ACM SIGPLAN 1998 conference on Programming language design and implementation (PLDI '98). Association for Computing Machinery, New York, NY, USA, 280–290. https://doi.org/10.1145/277650.277740

https://ei.cs.vt.edu/~cs5314/presentations/Group2PLDI.pdf

**Comment by microctar** [comment]
MUCHNICK, Steven, et al. Advanced compiler design implementation. Morgan kaufmann, 1997.

**Comment by zhangzhimin** [comment]
至少刚开始不需要沙盒, 先在不同模式下激活数组的越界检查即可. 比如Tensor, Array, DynamicArray等做检查, 种类是有限的,并且也容易做.
