### ISSUE TITLE
vscode的般若插件开发

### ISSUE THREAD

**Issue by zhangzhimin** [matazure/prajna#6]
开发类似于般若的插件, 由三个子任务构成

1. 代码高亮
2. 智能提示
3. 代码调试

**Comment by microctar** [comment]
我来尝试实现一下

**Comment by microctar** [comment]
> 智能提示的功能比想象中的复杂不少, 目前存在一个比较难的问题就是, 我们采用的解析库是boost::spirit, 获取的是AST, 且不太能获取lossless syntax tree.

没错，ast仅包含必要的信息，丢弃了空格、注释，一般用于静态分析。

**Comment by microctar** [comment]
> 开发类似于般若的插件, 由三个子任务构成
> 
> 1. 代码高亮
> 2. 智能提示
> 3. 代码调试

有关于代码高亮这一块，LSP相关定义在[Semantic Tokens](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens)。
相关讨论为:
- microsoft/language-server-protocol#682
- microsoft/language-server-protocol#513
- microsoft/language-server-protocol#18

**Comment by microctar** [comment]
I will mark this as a dup of https://github.com/Microsoft/language-server-protocol/issues/513 since having this will allow syntax highlighting as well (and we will not have two different approaches).

In general it is our expierence that syntax highlighting must be fast and it best done inside the editor itself. So requesting this from the server might not be optimal.

_Originally posted by @dbaeumer in https://github.com/microsoft/language-server-protocol/issues/682#issuecomment-486676262_

**Comment by microctar** [comment]
目前代码高亮的最低成本实现，即是基于[tree-sitter](https://tree-sitter.github.io/tree-sitter)构建相关语言的concrete syntax tree，快速解析单文件内容，捕获每一次键入，并实用tree-sitter内置的查询语法提取类型信息，匹配主题设置。

- [tree-sitter: Basic Parsing](https://tree-sitter.github.io/tree-sitter/using-parsers#basic-parsing)
- [tree-sitter: Advanced Parsing](https://tree-sitter.github.io/tree-sitter/using-parsers#advanced-parsing)
- [tree-sitter: Pattern Matching with Queries](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries)

**Comment by microctar** [comment]
有关于智能提示的部分资料：

- [Persistence, façades and Roslyn’s red-green trees](https://ericlippert.com/2012/06/08/red-green-trees/)
- [Red Green Syntax Trees - an Overview](https://willspeak.me/2021/11/24/red-green-syntax-trees-an-overview.html)

**Comment by microctar** [comment]
> 开发类似于般若的插件, 由三个子任务构成
> 
> 1. 代码高亮
> 2. 智能提示
> 3. 代码调试

有关于代码调试这一块，Microsoft制定了一个协议：[Debug Adapter Protocol](https://github.com/Microsoft/debug-adapter-protocol)

## 标准
 
- [specification](https://microsoft.github.io/debug-adapter-protocol/specification)

## 实现

- [codelldb](https://github.com/vadimcn/codelldb)
- [netcoredbg](https://github.com/Samsung/netcoredbg)

## Misc
- [rust-lang/llvm-project](https://github.com/rust-lang/llvm-project/commit/2abffbf977a9e8c6ca4174a08fe5c4d7781f0aac)

**Comment by zhangzhimin** [comment]
https://github.com/matazure/vscode-prajna-tools
暂时实现了代码高亮, 先关闭任务, 回头时机合适再继续
